import os
import sys
import json
import time
import shutil
import argparse
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from ultralytics import YOLO

from scripts.common import ROOT_DIR, CONFIGS_DIR, REPORTS_DIR, load_products_config, get_device

def evaluate_sku_model(
    model_path: str = "models/trained/best.pt",
    data_yaml: str = "configs/products.yaml",
    split: str = "test",
    imgsz: int = 640,
    batch: int = 16,
    conf_thresh: float = 0.25,
    iou_thresh: float = 0.60,
    output_dir: str = None
):
    print("=" * 65)
    print(" SmartRetail AI - Independent Test Evaluation Suite")
    print("=" * 65)

    model_file = Path(model_path)
    if not model_file.exists():
        raise FileNotFoundError(f"Model file not found: {model_path}")

    products_cfg = load_products_config(data_yaml)
    names = products_cfg.get("names", {})
    sku_ids = products_cfg.get("sku_ids", {})

    reports_dir = Path(output_dir) if output_dir else REPORTS_DIR
    reports_dir.mkdir(parents=True, exist_ok=True)

    print(f"Evaluating Checkpoint: {model_file}")
    print(f"Evaluation Split:      '{split}' split ONLY (Zero Data Leakage)")
    print(f"Confidence Threshold:  {conf_thresh}")
    print(f"IoU Threshold:         {iou_thresh}")
    print("-" * 65)

    model = YOLO(str(model_file))

    # Run validation specifically on the test split
    metrics = model.val(
        data=str(data_yaml),
        split=split,
        imgsz=imgsz,
        batch=batch,
        conf=conf_thresh,
        iou=iou_thresh,
        device=get_device(),
        plots=True,
        save_json=True
    )

    # Extract overall metrics
    map50 = float(metrics.box.map50)
    map50_95 = float(metrics.box.map)
    precision = float(metrics.box.mp)
    recall = float(metrics.box.mr)
    f1 = 2 * (precision * recall) / (precision + recall + 1e-6)

    print("\n" + "=" * 65)
    print(f" Overall Performance Summary ({split.upper()} SPLIT)")
    print("=" * 65)
    print(f"  Precision:       {precision * 100:.2f}%")
    print(f"  Recall:          {recall * 100:.2f}%")
    print(f"  F1 Score:        {f1 * 100:.2f}%")
    print(f"  mAP@0.50:        {map50 * 100:.2f}%")
    print(f"  mAP@0.50-0.95:   {map50_95 * 100:.2f}%")
    print("-" * 65)

    # Per-class breakdown
    class_results = []
    print(f"\n{'SKU ID':<10} {'Product Name':<22} {'P (%)':<10} {'R (%)':<10} {'mAP50 (%)':<12}")
    print("-" * 65)

    for cid, cname in names.items():
        sku_code = sku_ids.get(cid, f"SKU{int(cid)+1:03d}")
        try:
            cp = float(metrics.box.p[int(cid)]) * 100
            cr = float(metrics.box.r[int(cid)]) * 100
            cmap50 = float(metrics.box.maps[int(cid)]) * 100
        except Exception:
            cp, cr, cmap50 = 0.0, 0.0, 0.0

        class_results.append({
            "class_id": int(cid),
            "sku_id": sku_code,
            "product_name": cname,
            "precision": round(cp, 2),
            "recall": round(cr, 2),
            "map50": round(cmap50, 2)
        })
        print(f"{sku_code:<10} {cname:<22} {cp:<10.1f} {cr:<10.1f} {cmap50:<12.1f}")

    # Save metrics.json
    summary_data = {
        "evaluation_timestamp": time.strftime("%Y-%m-%d %H:%M:%S"),
        "model": str(model_file.name),
        "split": split,
        "overall": {
            "precision": round(precision, 4),
            "recall": round(recall, 4),
            "f1_score": round(f1, 4),
            "map50": round(map50, 4),
            "map50_95": round(map50_95, 4)
        },
        "per_class": class_results
    }

    json_file = reports_dir / "metrics.json"
    with open(json_file, "w", encoding="utf-8") as f:
        json.dump(summary_data, f, indent=2)
    print(f"\n[Saved] Metrics JSON written to: {json_file}")

    # Copy confusion matrix if generated by Ultralytics
    val_save_dir = getattr(metrics, "save_dir", None)
    if val_save_dir and Path(val_save_dir).exists():
        cm_src = Path(val_save_dir) / "confusion_matrix.png"
        if cm_src.exists():
            shutil.copy2(cm_src, reports_dir / "confusion_matrix.png")
            print(f"[Saved] Confusion Matrix: {reports_dir / 'confusion_matrix.png'}")

    # Generate HTML report
    generate_html_report(summary_data, reports_dir / "evaluation_report.html")
    print(f"[Saved] HTML Evaluation Report: {reports_dir / 'evaluation_report.html'}")

    return summary_data

def generate_html_report(data: dict, out_path: Path):
    overall = data["overall"]
    rows = ""
    for c in data["per_class"]:
        status_color = "#10b981" if c["map50"] >= 75.0 else ("#f59e0b" if c["map50"] >= 50.0 else "#f43f5e")
        rows += f"""
        <tr>
            <td><code>{c['sku_id']}</code></td>
            <td><strong>{c['product_name']}</strong></td>
            <td>{c['precision']:.1f}%</td>
            <td>{c['recall']:.1f}%</td>
            <td><strong style="color:{status_color};">{c['map50']:.1f}%</strong></td>
        </tr>
        """

    html = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SmartRetail AI - SKU Model Evaluation Report</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: #0f172a; color: #f8fafc; padding: 30px; }}
        .card {{ max-width: 900px; margin: 0 auto; background: #1e293b; border-radius: 12px; padding: 28px; border: 1px solid #334155; }}
        h1 {{ margin-top: 0; color: #38bdf8; font-size: 22px; }}
        .sub {{ color: #94a3b8; font-size: 13px; margin-bottom: 24px; }}
        .kpi-grid {{ display: grid; grid-template-columns: repeat(4, 1fr); gap: 14px; margin-bottom: 24px; }}
        .kpi {{ background: #0f172a; padding: 14px; border-radius: 8px; border: 1px solid #334155; }}
        .kpi-title {{ font-size: 11px; text-transform: uppercase; color: #94a3b8; }}
        .kpi-val {{ font-size: 24px; font-weight: 700; color: #38bdf8; margin-top: 4px; }}
        table {{ width: 100%; border-collapse: collapse; margin-top: 14px; font-size: 13px; }}
        th {{ background: #0f172a; text-align: left; padding: 10px; color: #94a3b8; border-bottom: 2px solid #334155; }}
        td {{ padding: 10px; border-bottom: 1px solid #334155; }}
    </style>
</head>
<body>
    <div class="card">
        <h1>SmartRetail AI — SKU Object Detector Evaluation</h1>
        <div class="sub">Model: <strong>{data['model']}</strong> | Evaluated on <strong>{data['split'].upper()} Split</strong> | Generated: {data['evaluation_timestamp']}</div>

        <div class="kpi-grid">
            <div class="kpi"><div class="kpi-title">mAP @ 0.50</div><div class="kpi-val">{overall['map50']*100:.1f}%</div></div>
            <div class="kpi"><div class="kpi-title">mAP @ 0.50-0.95</div><div class="kpi-val">{overall['map50_95']*100:.1f}%</div></div>
            <div class="kpi"><div class="kpi-title">Precision</div><div class="kpi-val">{overall['precision']*100:.1f}%</div></div>
            <div class="kpi"><div class="kpi-title">Recall</div><div class="kpi-val">{overall['recall']*100:.1f}%</div></div>
        </div>

        <h3>Per-SKU Performance Breakdown</h3>
        <table>
            <thead>
                <tr><th>SKU</th><th>Product Name</th><th>Precision</th><th>Recall</th><th>mAP@0.50</th></tr>
            </thead>
            <tbody>
                {rows}
            </tbody>
        </table>
    </div>
</body>
</html>"""
    out_path.write_text(html, encoding="utf-8")

def main():
    parser = argparse.ArgumentParser(description="Evaluate trained SKU model on independent test dataset")
    parser.add_argument("--model", default="models/trained/best.pt", help="Path to trained checkpoint")
    parser.add_argument("--data", default="configs/products.yaml", help="Path to products.yaml")
    parser.add_argument("--split", default="test", help="Dataset split to evaluate on (test or val)")
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--conf", type=float, default=0.25)
    parser.add_argument("--output", default="reports", help="Output directory for reports")
    args = parser.parse_args()

    evaluate_sku_model(
        model_path=args.model,
        data_yaml=args.data,
        split=args.split,
        imgsz=args.imgsz,
        batch=args.batch,
        conf_thresh=args.conf,
        output_dir=args.output
    )

if __name__ == "__main__":
    main()
