"""
SmartRetail AI - Synthetic Retail Demo Simulator
=================================================
IMPORTANT DISCLAIMER & HONEST SYSTEM ARCHITECTURE NOTE:
This module contains an OpenCV color/coordinate heuristic simulator calibrated
exclusively for the synthetic retail simulation video ('videos/store.mp4').
Because the bundled store video renders supermarket shelves and shoppers as
color-coded geometric blocks, this heuristic matches those colors and coordinates.

It is NOT a trained neural network and will not recognize products in real CCTV
or smartphone footage. All detections generated by this module are explicitly
tagged with `source="demo_simulation"` and surfaced to the UI as 'DEMO SIMULATION'.

When a real custom SKU model is trained and saved to 'models/trained/best.pt',
the system automatically switches to `source="trained_sku_model"` ('TRAINED MODEL').
"""

import cv2
import numpy as np
from typing import List, Tuple
from app.detection.results import Detection

class DemoShelfSimulator:
    """
    Fallback shelf and shopper detector for the synthetic retail preview environment.
    """

    def __init__(self):
        self.sku_map = {
            "Fanta Orange": "SKU001",
            "Pringles Original": "SKU002",
            "Oreo": "SKU003",
            "Amul Taaza": "SKU004",
            "Real Orange Juice": "SKU005",
            "Dove Soap": "SKU006",
            "Coca Cola": "SKU007",
            "Lays Classic": "SKU008",
            "Dairy Milk": "SKU009",
            "Colgate Paste": "SKU010"
        }

    @staticmethod
    def _iou(boxA: Tuple[int, int, int, int], boxB: Tuple[int, int, int, int]) -> float:
        xA = max(boxA[0], boxB[0])
        yA = max(boxA[1], boxB[1])
        xB = min(boxA[2], boxB[2])
        yB = min(boxA[3], boxB[3])
        interArea = max(0, xB - xA) * max(0, yB - yA)
        boxAArea = (boxA[2] - boxA[0]) * (boxA[3] - boxA[1])
        boxBArea = (boxB[2] - boxB[0]) * (boxB[3] - boxB[1])
        return interArea / float(boxAArea + boxBArea - interArea + 1e-5)

    def detect_products(self, frame: np.ndarray) -> List[Detection]:
        if frame is None or frame.size == 0:
            return []

        h, w, _ = frame.shape
        detections = []
        hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)

        # 1. Shelf B: Beverages (x: 40-520, y: 330-580)
        shelf_b_mask = np.zeros((h, w), dtype=np.uint8)
        shelf_b_mask[330:580, 40:520] = 255

        # Fanta Orange
        fanta_mask = cv2.inRange(hsv, np.array([8, 140, 140]), np.array([24, 255, 255]))
        fanta_mask = cv2.bitwise_and(fanta_mask, shelf_b_mask)
        f_contours, _ = cv2.findContours(fanta_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in f_contours:
            x, y, bw, bh = cv2.boundingRect(cnt)
            if 18 <= bw <= 55 and 35 <= bh <= 90:
                detections.append(Detection(
                    class_id=0, class_name="Fanta Orange", confidence=0.96,
                    bbox=(x, y, x + bw, y + bh), product_name="Fanta Orange",
                    sku_id="SKU001", source="demo_simulation"
                ))

        # Real Orange Juice
        juice_mask = cv2.inRange(hsv, np.array([90, 100, 100]), np.array([125, 255, 255]))
        juice_mask = cv2.bitwise_and(juice_mask, shelf_b_mask)
        j_contours, _ = cv2.findContours(juice_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in j_contours:
            x, y, bw, bh = cv2.boundingRect(cnt)
            if 20 <= bw <= 60 and 40 <= bh <= 90 and x < 350:
                detections.append(Detection(
                    class_id=4, class_name="Real Orange Juice", confidence=0.94,
                    bbox=(x, y, x + bw, y + bh), product_name="Real Orange Juice",
                    sku_id="SKU005", source="demo_simulation"
                ))

        # Coca Cola
        coke_mask = cv2.inRange(hsv, np.array([165, 120, 80]), np.array([180, 255, 240]))
        coke_mask = cv2.bitwise_and(coke_mask, shelf_b_mask)
        c_contours, _ = cv2.findContours(coke_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in c_contours:
            x, y, bw, bh = cv2.boundingRect(cnt)
            if 18 <= bw <= 55 and 35 <= bh <= 90 and x >= 350:
                detections.append(Detection(
                    class_id=6, class_name="Coca Cola", confidence=0.95,
                    bbox=(x, y, x + bw, y + bh), product_name="Coca Cola",
                    sku_id="SKU007", source="demo_simulation"
                ))

        # 2. Shelf A: Snacks & Biscuits (x: 40-520, y: 40-270)
        shelf_a_mask = np.zeros((h, w), dtype=np.uint8)
        shelf_a_mask[40:270, 40:520] = 255

        # Pringles
        pring_mask = cv2.inRange(hsv, np.array([0, 130, 100]), np.array([10, 255, 255]))
        pring_mask = cv2.bitwise_and(pring_mask, shelf_a_mask)
        p_contours, _ = cv2.findContours(pring_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in p_contours:
            x, y, bw, bh = cv2.boundingRect(cnt)
            if 18 <= bw <= 55 and 35 <= bh <= 90 and x < 180:
                detections.append(Detection(
                    class_id=1, class_name="Pringles Original", confidence=0.95,
                    bbox=(x, y, x + bw, y + bh), product_name="Pringles Original",
                    sku_id="SKU002", source="demo_simulation"
                ))

        # Oreo
        oreo_mask = cv2.inRange(hsv, np.array([100, 120, 80]), np.array([130, 255, 220]))
        oreo_mask = cv2.bitwise_and(oreo_mask, shelf_a_mask)
        o_contours, _ = cv2.findContours(oreo_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in o_contours:
            x, y, bw, bh = cv2.boundingRect(cnt)
            if 20 <= bw <= 60 and 35 <= bh <= 90 and 180 <= x < 320:
                detections.append(Detection(
                    class_id=2, class_name="Oreo", confidence=0.93,
                    bbox=(x, y, x + bw, y + bh), product_name="Oreo",
                    sku_id="SKU003", source="demo_simulation"
                ))

        # Lays Classic
        lays_mask = cv2.inRange(hsv, np.array([20, 150, 150]), np.array([35, 255, 255]))
        lays_mask = cv2.bitwise_and(lays_mask, shelf_a_mask)
        l_contours, _ = cv2.findContours(lays_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in l_contours:
            x, y, bw, bh = cv2.boundingRect(cnt)
            if 20 <= bw <= 60 and 35 <= bh <= 90 and x >= 320:
                detections.append(Detection(
                    class_id=7, class_name="Lays Classic", confidence=0.94,
                    bbox=(x, y, x + bw, y + bh), product_name="Lays Classic",
                    sku_id="SKU008", source="demo_simulation"
                ))

        # 3. Shelf C: Dairy & Essentials (x: 800-1240, y: 40-270)
        shelf_c_mask = np.zeros((h, w), dtype=np.uint8)
        shelf_c_mask[40:270, 800:1240] = 255

        # Amul Milk
        milk_mask = cv2.inRange(hsv, np.array([0, 0, 175]), np.array([180, 45, 235]))
        milk_mask = cv2.bitwise_and(milk_mask, shelf_c_mask)
        m_contours, _ = cv2.findContours(milk_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in m_contours:
            x, y, bw, bh = cv2.boundingRect(cnt)
            if 20 <= bw <= 55 and 35 <= bh <= 90 and x < 970:
                detections.append(Detection(
                    class_id=3, class_name="Amul Taaza", confidence=0.93,
                    bbox=(x, y, x + bw, y + bh), product_name="Amul Taaza",
                    sku_id="SKU004", source="demo_simulation"
                ))

        # Dove Soap
        dove_mask = cv2.inRange(hsv, np.array([0, 0, 240]), np.array([180, 20, 255]))
        dove_mask = cv2.bitwise_and(dove_mask, shelf_c_mask)
        d_contours, _ = cv2.findContours(dove_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        for cnt in d_contours:
            x, y, bw, bh = cv2.boundingRect(cnt)
            if 20 <= bw <= 60 and 30 <= bh <= 85 and x >= 970:
                detections.append(Detection(
                    class_id=5, class_name="Dove Soap", confidence=0.92,
                    bbox=(x, y, x + bw, y + bh), product_name="Dove Soap",
                    sku_id="SKU006", source="demo_simulation"
                ))

        return detections

    def detect_people_fallback(self, frame: np.ndarray) -> List[Detection]:
        """
        Calibrated people detector for synthetic retail preview video ('videos/store.mp4').
        Accurately detects all staff and shoppers using human figure geometry filters (24-45px width,
        55-90px height) and morphological closing to encapsulate the complete person in 1 clean box.
        """
        h, w, _ = frame.shape
        kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (20, 30))
        person_raw_boxes = []

        # 1. Staff Uniform BGR: Cyan (212, 182, 6)
        staff_colors = [(212, 182, 6)]
        for bgr in staff_colors:
            lower = np.array([max(0, c - 25) for c in bgr], dtype=np.uint8)
            upper = np.array([min(255, c + 25) for c in bgr], dtype=np.uint8)
            mask = cv2.inRange(frame, lower, upper)
            cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            for c in cnts:
                x, y, bw, bh = cv2.boundingRect(c)
                if 20 <= bw <= 45 and 35 <= bh <= 55:
                    role = "Cashier" if x >= 1050 else "Floor Associate"
                    person_raw_boxes.append((x - 6, y - 26, x + bw + 6, y + bh + 8, "staff", role))

        # 2. Shopper BGR Palette
        shopper_colors = [
            (180, 120, 50), (60, 160, 100), (80, 80, 200), (160, 80, 160),
            (40, 140, 220), (220, 80, 80), (120, 180, 60), (190, 60, 140)
        ]
        for bgr in shopper_colors:
            lower = np.array([max(0, c - 25) for c in bgr], dtype=np.uint8)
            upper = np.array([min(255, c + 25) for c in bgr], dtype=np.uint8)
            mask = cv2.inRange(frame, lower, upper)
            mask = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel)
            cnts, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
            for c in cnts:
                x, y, bw, bh = cv2.boundingRect(c)
                # Matches human shopper figure dimensions (24-45px width, 55-90px height)
                if 24 <= bw <= 45 and 55 <= bh <= 90:
                    person_raw_boxes.append((x - 6, y - 8, x + bw + 6, y + bh + 8, "customer", None))

        def _dist(b1, b2):
            c1 = ((b1[0] + b1[2]) / 2.0, (b1[1] + b1[3]) / 2.0)
            c2 = ((b2[0] + b2[2]) / 2.0, (b2[1] + b2[3]) / 2.0)
            return np.hypot(c1[0] - c2[0], c1[1] - c2[1])

        # De-duplicate: Keep only 1 detection per individual person (IoU > 0.20 or center distance < 25px)
        kept_boxes = []
        for pb in person_raw_boxes:
            box_coords = (max(0, pb[0]), max(0, pb[1]), min(w, pb[2]), min(h, pb[3]))
            if not any(self._iou(box_coords, kb[0]) > 0.20 or _dist(box_coords, kb[0]) < 25.0 for kb in kept_boxes):
                kept_boxes.append((box_coords, pb[4], pb[5]))

        detections = []
        for box_coords, ptype, srole in kept_boxes:
            detections.append(Detection(
                class_id=0,
                class_name="person",
                confidence=0.96,
                bbox=box_coords,
                product_name=None,
                sku_id=None,
                person_type=ptype,
                staff_role=srole,
                source="demo_simulation"
            ))

        return detections
